### ISSUE TITLE
Arrumar SideMenu

### ISSUE THREAD

**Issue by gabibguedes** [Dulce-Work-Schedule/2018.1-Dulce_App#391]
Nesse épico será realizado:
- [x] Estudar como estilizar o side menu
- [ ] Estilizar o side menu
- [ ] Adicionar botão "Sanduíche" na WeekSchedule
